#!/usr/bin/env bash

# use errexit
set -eu

cleanup() {
    echo "Goodbye!"
}
trap cleanup EXIT

prql-compile() { 
  IFS=" "
  local query="$1"
  local options="${@:2}"
  if [ -n "${PRQL_COMPILE_OPTIONS:-}" ]; then
    #echo "Using PRQL_COMPILE_OPTIONS=$PRQL_COMPILE_OPTIONS" >&2
    options="${options[@]} ${PRQL_COMPILE_OPTIONS}"
  fi
  PRQL_COMPILE_OUTPUT="$( echo "$query" | eval "prqlc compile - - $options" )"
  if [[ $? -ne 0 ]]; then
    echo -e "\n# QUERY\n\n$query\n\n"
    return 1
  fi
}

capitalize() {
  local input="$1"
  local first_letter="$(echo "${input:0:1}" | tr '[:lower:]' '[:upper:]')"
  local rest_of_string="${input:1}"
  echo "${first_letter}${rest_of_string}"
}

prql-import() { 
  # FIXME: Add support for aliases
  local output=""
  local separator="${2:-__}"
  local prefix="${3:-$1}"
  local prql_lib_path="${PRQL_LIB_PATH:-.}"
  local found=false
  PRQL_LIB_PATH=""
  #echo "Using PRQL_LIB_PATH=$prql_lib_path" >&2
  IFS=":"
  for lib_dir in $prql_lib_path; do
    if ([[ -d "$lib_dir/$1" ]] && [[ -f "$lib_dir/$1/$(capitalize $1).prql" ]]); then
      # found a library
      pushd "$lib_dir/$1" > /dev/null
      prql-lib "$(capitalize $1).prql" "$separator" "$prefix"
      popd > /dev/null
      output="$PRQL_LIB_OUTPUT"
      #echo "Imported $lib_dir/$1/$(capitalize $1).prql" >&2
      # Also source .env file if present for prql-exec
      if [ -f "$lib_dir/$1/.env" ]; then
        #cat "$lib_dir/$1/.env" >&2
	set -a
        source "$lib_dir/$1/.env"
	set +a
      fi
      found=true
      break
    elif [[ -f "$lib_dir/$1.prql" ]]; then
      # found a module
      output=$(cat "$lib_dir/$1.prql")
      #echo "Imported $lib_dir/$1.prql" >&2
      found=true
      break
    fi
  done
  if [ "$found" = false ]; then
    echo "ERROR: Could not import $1."
    return 1
  fi
  # apply the prefix to all let statements
  output=$(echo "$output" | sed -r "s/^let[ ]+/let $prefix$separator/")
  PRQL_IMPORT_OUTPUT="$output"
}

prql-lib() { 
  local input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
  local output="$input"
  local separator="${2:-__}"
  # Define the pattern to match lines
  local import_pattern="^import[[:space:]]\{1,\}[[:alnum:]_-]\{1,\}[[:space:]]\{0,\}\(as[[:space:]]\{1,\}[[:alnum:]_-]\{1,\}\)\{0,1\}$"
  # Use sed to extract lines matching the pattern and capture the two words following "import"
  local import_matches=$(echo "$output" | sed -n "/$import_pattern/p")
  # Iterate over the matches using a for loop
  IFS=$'\n'  # Set the Internal Field Separator to newline to iterate over lines
  for line in $import_matches; do
    if [[ "$line" =~ ^import[[:space:]]+([[:alnum:]_-]+)[[:space:]]*(as)?[[:space:]]*([[:alnum:]_-]+)?[[:space:]]*$ ]]; then
      local library_name="${BASH_REMATCH[1]}"
      local library_alias="${BASH_REMATCH[3]}"
      local prefix="${3:-$library_name}"
      prql-import "$library_name" "$separator" "$prefix"
      local import_replacement="$PRQL_IMPORT_OUTPUT"
      # Replace the import statement with the code from the module/library
      output=$(echo "$output" | awk -v import_replacement="$import_replacement" '{gsub("'"$line"'", import_replacement)}1')
      # Replace references to the module/library
      output=$(echo "$output" | sed -r "s/\<$library_alias\>\./$prefix$separator/g")
    fi
  done
  PRQL_LIB_OUTPUT="$output"
}

prql-exec-fn() {
  # Looks for PRQL_EXEC_COMMAND and passes output to that if present
  local input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
  local options="${@:2}"
  prql-lib "$input"
  local query="$PRQL_LIB_OUTPUT"
  prql-compile "$query"
  if [[ $? -ne 0 ]]; then
    return $?
  fi
  local sql="$PRQL_COMPILE_OUTPUT"
  #echo "$( env | grep PRQL_ )" >&2
  if [ -n "${PRQL_EXEC_COMMAND:-}" ]; then
    #echo "Using PRQL_EXEC_COMMAND=$PRQL_EXEC_COMMAND $options" >&2
    echo -e "$sql\n;" | eval "$PRQL_EXEC_COMMAND $options"
  else
    # When no PRQL_EXEC_COMMAND is given we behave just like
    # prqlc compile and echo the SQL.
    echo $sql
  fi
}

input=$( ([ $# -eq 0 ] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
prql-exec-fn "$input" "${@:2}"
