#!/usr/bin/env bash

# use errexit
set -eu

prql-compile() { 
  IFS=" "
  local query="$1"
  local options="${@:2}"
  if [ -n "${PRQL_COMPILE_OPTIONS:-}" ]; then
    #echo "Using PRQL_COMPILE_OPTIONS=$PRQL_COMPILE_OPTIONS" >&2
    options="${options[@]} ${PRQL_COMPILE_OPTIONS}"
  fi
  PRQL_COMPILE_OUTPUT="$( echo "$query" | eval "prqlc compile - - $options" )"
  if [[ $? -ne 0 ]]; then
    echo -e "\n# QUERY\n\n$query\n\n"
    return 1
  fi
}

capitalize() {
  local input="$1"
  local first_letter="$(echo "${input:0:1}" | tr '[:lower:]' '[:upper:]')"
  local rest_of_string="${input:1}"
  echo "${first_letter}${rest_of_string}"
}

prql-import() { 
  # looks for $name on the $prql_lib_path
  local import_name="$1"
  local output=""
  local prql_lib_path="${2:-$PRQL_LIB_PATH}"
  local separator="${3:-__}"
  local import_alias="${4:-}"
  local prefix="${5:-}"
  if [ "$import_alias" == "" ]; then
    # When there is no $import_alias then treat them as global imports.
    separator=""
  fi
  local found=false
  #echo "Using PRQL_LIB_PATH=$prql_lib_path" >&2
  IFS=":"
  for lib_dir in $prql_lib_path; do
    if ([[ -d "$lib_dir/$import_name" ]] && [[ -f "$lib_dir/$import_name/$(capitalize $import_name).prql" ]]); then
      # found a library
      pushd "$lib_dir/$import_name" > /dev/null
      prql-lib "$(cat "$(capitalize $import_name).prql")" "." "$separator" "$import_alias" "$prefix$import_alias$separator"
      popd > /dev/null
      output="$PRQL_LIB_OUTPUT"
      #echo "Imported $lib_dir/$import_name/$(capitalize $import_name).prql" >&2
      # Also source .env file if present for prql-exec
      if [ -f "$lib_dir/$import_name/.env" ]; then
        #cat "$lib_dir/$import_name/.env" >&2
	set -a
        source "$lib_dir/$import_name/.env"
	set +a
      fi
      found=true
      break
    elif [[ -f "$lib_dir/$import_name.prql" ]]; then
      # found a module
      output=$(cat "$lib_dir/$import_name.prql")
      #echo "Imported $lib_dir/$import_name.prql" >&2
      found=true
      break
    fi
  done
  if [ "$found" = false ]; then
    echo "ERROR: Could not import $import_name."
    return 1
  fi
  # For let statements, we prefix them with the current module name which is enough
  # as this will be repeated as the code is passed up the stack.
  output=$(echo "$output" | sed -r "s/^([[:space:]]*)let[[:space:]]+/\1let $import_alias$separator/g")
  PRQL_IMPORT_OUTPUT="$output"
}

prql-lib() { 
  # Looks for import statements in the current input and then calls prql-import for those.
  local input="$1"
  local output="$input"
  local separator="${3:-__}"
  local prefix="${5:-}"
  # Define the pattern to match lines
  local import_pattern="^import[[:space:]]\{1,\}\.\{0,1\}[[:alnum:]_-]\{1,\}[[:space:]]\{0,\}\(as[[:space:]]\{1,\}[[:alnum:]_-]\{0,\}\)\{0,1\}$"
  # Use sed to extract lines matching the pattern and capture the two words following "import"
  local import_matches=$(echo "$output" | sed -n "/$import_pattern/p")
  # Iterate over the matches using a for loop
  IFS=$'\n'  # Set the Internal Field Separator to newline to iterate over lines
  local line
  for line in $import_matches; do
    if [[ "$line" =~ ^import[[:space:]]+(\.)?([[:alnum:]_-]+)[[:space:]]*(as)?[[:space:]]*([[:alnum:]_-]+)?[[:space:]]*$ ]]; then
      local prql_lib_path="${BASH_REMATCH[1]}"
      if [[ "$prql_lib_path" == "" ]]; then
        prql_lib_path="$PRQL_LIB_PATH"
      fi
      local import_name="${BASH_REMATCH[2]}"
      local import_as="${BASH_REMATCH[3]}"
      if [ "$import_as" == "as" ]; then
	# When there is an "as" present we use the match as found.
	# In particular, an empty inport_alias signifies importing
	# things into the global namespace.
	local import_alias="${BASH_REMATCH[4]}"
      else
        # Without an "as" we use the $import_name as the alias.
	local import_alias="$import_name"
      fi
      prql-import "$import_name" "$prql_lib_path" "$separator" "$import_alias"
      local import_replacement="$PRQL_IMPORT_OUTPUT"
      # Replace the import statement with the code from the module/library
      output=$(echo "$output" | awk -v import_replacement="$import_replacement" '{gsub("'"$line"'", import_replacement)}1')
      # For references to the current module/library, we have to prefix with the
      # full prefix up to this point in order to avoid name collisions.
      # This will only be done once so we have to apply the full prefix.
      # This is pretty hacky and unsafe so users should try to avoid name collisions.
      # FIXME: do we need the :space: here or is \b enough?
      output=$(echo "$output" | sed -r "s/([[:space:].]|\b)$import_alias\./\1$prefix$import_alias$separator/g")
    fi
  done
  PRQL_LIB_OUTPUT="$output"
}

prql-exec-fn() {
  # These variables are not local so that we can display them in the error handler.
  input="$1"
  user_options="${@:2}"			# Override options take preference
  # Reset the other global variables
  # Note: we can't make these local because we want the error handler to have access to them.
  unset query
  unset sql
  unset default_options
  unset PRQL_EXEC_OPTIONS
  unset PRQL_EXEC_COMMAND

  # Process the imports
  prql-lib "$input"
  query="$PRQL_LIB_OUTPUT"

  # Compile to SQL
  prql-compile "$query"
  sql="$PRQL_COMPILE_OUTPUT"

  # Determine command options
  # This can only be done after prql-lib because that loads the PRQL_EXEC_OPTIONS
  default_options="${PRQL_EXEC_OPTIONS:-}"
  PRQL_EXEC_OPTIONS="${user_options:-$default_options}"

  # Execute the command
  if [ -n "${PRQL_EXEC_COMMAND:-}" ]; then
    eval "$PRQL_EXEC_COMMAND"
  else
    # When no PRQL_EXEC_COMMAND is given we behave just like
    # prqlc compile and echo the SQL.
    echo $sql
  fi
}

split-docs() {
  local remaining="$1"
  local doc=''
  nl=$'\n'
  regex_doc="^($nl?-{3,}$nl)?(.+)($|$nl-{3,}$nl.*)"
  while [ -n "$remaining" ]; do
    if [[ "$remaining" =~ $regex_doc ]]; then
      doc="${BASH_REMATCH[2]}"
      remaining="${BASH_REMATCH[3]}"
      #echo -e "Found doc:\n'''\n$doc\n'''\n"
      prql-exec-fn "$doc" "${@:2}"
    else
      echo -e "ERROR: Couldn't parse input:\n'''\n$remaining\n'''\n"
      return 1
    fi
  done
}

# Add error handling
error_handler() {
  echo -e "\nERROR:" >&2
  echo -e "\ninput=$input" >&2
  echo -e "\nquery=${query:-NOT GENERATED}" >&2
  echo -e "\nsql=${sql:-NOT GENERATED}" >&2
  echo -e "\nPRQL_EXEC_COMMAND=${PRQL_EXEC_COMMAND:-NOT GENERATED}" >&2
}
trap error_handler EXIT

# Standardise input
script_input=$( ([ $# -eq 0 ] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )

# Process the input
split-docs "$script_input" "${@:2}"

# If we got here we succeeded so untrap the exit error handler
trap - EXIT
